### ISSUE TITLE
FeedsClient app v1.1.1 launch fail with exception

### ISSUE THREAD

**Issue by midcielab** [midcielab/feeds-client#2]
**Symptom**

On graalvm java 11 launch fail, exception as below

```java
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.midcielab.handler.FeedsHandler.<init>(FeedsHandler.java:30)
        at com.midcielab.handler.FeedsHandler.<clinit>(FeedsHandler.java:21)
        at com.midcielab.FeedsClient.main(FeedsClient.java:8)
Caused by: java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
        at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:573)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:598)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:585)
        at com.midcielab.utility.ConfigUtility.<clinit>(ConfigUtility.java:16)
        ... 3 more
```

**Comment by midcielab** [comment]
Add mutli-release flag in manifest by modify POM.xml, fix on v1.1.2
